medizininformatik-initiative/INTERPOLAR

R-etlutils/etlutils/R/lib_helper_functions.R
(cherry picked from commit 0ea942f3ed5eb95fd6fba539af0fa5d76f416f72)
=> U Fix missing URL_PORT_SPEC variable

R-etlutils/etlutils/R/lib_helper_functions.R, R-etlutils/etlutils/R/lib_sample_resources.R, R-etlutils/etlutils/man/polar_download_by_ids_and_crack_parallel.Rd, R-etlutils/etlutils/man/stopOnError.Rd, R-kds2db/README.md, R-kds2db/kds2db_config.toml
=> 126 kds2db kleine anpassungen für release v01

R-etlutils/etlutils/man/polar_download_by_ids_and_crack_parallel.Rd, R-kds2db/kds2db/R/Preparation_Create_TableStatements.R
=> 135 kds2db letzte fehlerbehebungen vor release v01

docker-compose.yml
=> substitute ${PWD} with ".", refs #158

Install.md, Postgres-cds_hub/Readme.md, docker-compose.yml, pgadmin_cds_hub.json
Ticket #155 gelöst.
Ticket kann nach dem Merge  geschlossen und Branch gelöscht werden. THX.
=> 155 pgadmin konfiguration aus den umgebungsvariablen docker compose env erzeugen

Postgres-cds_hub/init/16_cre_table_typ_log.sql, Postgres-cds_hub/init/template/template_copy_function_sub_single_table.sql, R-db2frontend/db2frontend/R/dbDatatoREDCap.R
- Reihenfolge Spalten bei FE Schnittstelle
- Template Anpassung Error  Msg
=> 251 fix dataviews for frontend

R-dataprocessor/dataprocessor/R/02_Create_Simple_Patient_And_Case_Presentation.R
=> 267 fuellen der neu dazugekommenen id spalten fuer patient fe und fall fe

R-db2frontend/db2frontend/R/dbDatatoREDCap.R
=> Split SQL R-Code to get data for each REDCap form separately.

Postgres-cds_hub/init/40_cre_table_typ_dataproc_in.sql, Postgres-cds_hub/init/42_cre_table_frontend_log.sql, Postgres-cds_hub/init/44_cre_table_frontend_in.sql, Postgres-cds_hub/init/60_dp_in_to_db_log.sql, Postgres-cds_hub/init/62_fe_in_to_db_log.sql, R-dataprocessor/dataprocessor/R/02_Create_Simple_Patient_And_Case_Presentation.R, R-db2frontend/db2frontend/R/dbDatatoREDCap.R
=> 276 dbdp mitfuehren der getypten daten id im dataprocessor

Postgres-cds_hub/DB_description.md
- die Dataflow.md muss noch verlinkt werden
=> 211 dokumentation db tabellen schemata

Dataflow.md, README.md, interpolar-model.3lgm
=> 302 datenflussbeschreibung verlinken und workflow nummern architektur grafik verwenden

R-cds2db/cds2db/R/00_Main.R, R-cds2db/cds2db/R/01_Get_PIDs.R, R-etlutils/etlutils/R/lib_logging.R
Die Log Messages sind so verbessert, dass klar ist, ob Daten vom Server geladen wurden und wenn ja, aus welchem Zeitraum und ob die Daten bereist in der DB vorhanden waren. Außerdem wird am Ende eine Message ausgegeben, die Erfolg oder Misserfolg verkündet.
closes #306
=> 306 modul erfolgreich durchgelaufen meldung am ende ausgeben

README.md
=> 222 empfehlung für dimensionierung anforderungen der vmcontainer cpu ram storage erstellen

REDCap-app/build/config/php.ini, REDCap-db/template_env-redcap-db, docker-compose.yml
Löst issue #318 nicht vollständig.
Löst issue #317
=> 318 frontend verändert gebutrstadatum

Postgres-cds_hub/init/10_cre_table_raw_cds2db_in.sql, Postgres-cds_hub/init/12_cre_table_raw_db_log.sql, Postgres-cds_hub/init/14_cre_table_typ_cds2db_in.sql, Postgres-cds_hub/init/16_cre_table_typ_log.sql, Postgres-cds_hub/init/18_cre_view_raw_type_diff_log.sql, Postgres-cds_hub/init/19_cre_view_typ_dataproc_all.sql, Postgres-cds_hub/init/20_take_over_check_date.sql, Postgres-cds_hub/init/21_cre_view_typ_cds2db_all.sql, Postgres-cds_hub/init/30_cds_in_to_db_log.sql, Postgres-cds_hub/init/31_cds_in_to_db_log.sql, Postgres-cds_hub/init/40_cre_table_typ_dataproc_in.sql, Postgres-cds_hub/init/42_cre_table_frontend_log.sql, Postgres-cds_hub/init/43_cre_table_frontend_log.sql, Postgres-cds_hub/init/44_cre_table_frontend_in.sql, Postgres-cds_hub/init/52_cre_view_fe_out.sql, Postgres-cds_hub/init/60_dp_in_to_db_log.sql, Postgres-cds_hub/init/62_fe_in_to_db_log.sql, R-cds2db/cds2db/R/Init_02_Create_Database_Scripts.R
=> Add descriptive header to generated SQL files

Postgres-cds_hub/init/02_db_config_tools.sql
=> 506 db statusanzeige erweitern des verarbeitungsprozesses

R-etlutils/etlutils/R/lib_fhir_search.R
=> 711 fhir search min patient age can be null

R-etlutils/etlutils/R/lib_db.R
=> Enable run cron job function from R code by DB toml parameter

Postgres-cds_hub/R-initcdstoolchain/initcdstoolchain/DESCRIPTION, R-cds2db/cds2db/DESCRIPTION, R-cdstoolchain/StartCDSToolChain.R, R-dataprocessor/dataprocessor/DESCRIPTION, R-dataprocessor/dataprocessor/R/01_Shared_Functions.R, R-dataprocessor/dataprocessor/R/02_Create_Simple_Patient_And_Case_Presentation.R, R-db2frontend/db2frontend/DESCRIPTION
=> 722 optimize database calls for observations

R-cds2db/StartRetrieval.R, R-cds2db/cds2db/R/00_Main.R, R-cdstoolchain/StartCDSToolChain.R, R-cdstoolchain/StartDebugCDSToolChain.R, R-dataprocessor/StartDataProcessor.R, R-dataprocessor/dataprocessor/R/00_Main.R, R-db2frontend/StartDB2Frontend.R, R-db2frontend/db2frontend/R/00_Main.R, R-etlutils/etlutils/R/lib_logging.R
=> Quit processes on error with return value 1

R-db2frontend/db2frontend/inst/extdata/RedcapDataDictionaryToFrontendTableDescription.R
=> 765 fix changed redcap list values delimiter in csv export
